### ISSUE TITLE
Similar Project

### ISSUE THREAD

**Issue by jaredsburrows** [emartynov/ios-app-with-gradle#1]
This is a very good idea. I have started a similar project here:

https://github.com/jaredsburrows/gradle-ios-plugin

and here the example:

https://github.com/jaredsburrows/gradle-ios-plugin-example

I just never got around to finish it and I may go back to it later. What have you done so far?

**Comment by emartynov** [comment]
Hey Jared!

Actually I wanted to have example for my talk about this plugin:
https://github.com/openbakery/gradle-xcodePlugin

But as for me the DSL for that project must be improved. I missed build types and build flavours, similar to android.

So I'm not going to create nothing new. But I was thinking to contribute to that plugin to have better DSL.

**Comment by jaredsburrows** [comment]
Nice. I will take a look at that.
